[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}
config = ""

[[language]]
name = "nix"
language-server = { command = "nil", args = [] }
auto-format = true
formatter = {command = 'nixfmt'}
config = ""
