[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}
config = ""

[[language]]
name = "ocaml"
file-types = ["ml"]
roots = ["dune-project"]
language-server = { command = "ocamllsp" }
auto-format = true
formatter = {command = 'ocamlformat', args = ["-", "--impl"]}

[[language]]
name = "nix"
language-server = { command = "nil", args = [] }
auto-format = true
formatter = {command = 'nixfmt'}
config = ""

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "go"

[[language]]
name = "html"
