[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.nil]
command = "nil"
args = []

[language-server.ocamllsp]
command = "ocamllsp"

[language-server.graphql-lsp]
command = "graphql-lsp"
args = ["server", "-m", "stream"]  

[language-server.helm-ls]
command = "helm_ls"
args = ["serve"]

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-servers = ["pyright-langserver"]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[[language]]
name = "ocaml"
file-types = ["ml"]
roots = ["dune-project"]
language-servers = ["ocamllsp"]
auto-format = true
formatter = {command = 'ocamlformat', args = ["-", "--impl"]}

[[language]]
name = "nix"
language-servers = ["nil"]
auto-format = true
formatter = {command = 'nixfmt'}

[[language]]
name = "graphql"
language-servers = ["graphql-lsp"]

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "go"

[[language]]
name = "hcl"

[[language]]
name = "tfvars"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }


[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }


[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "c"
auto-format = true

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["helm-ls"]
